[theme]
base="light"
primaryColor="#0D62FE"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#000000"
font="sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
